---
title: 'Distribution 6 DoF Experiences'
teaching: 10
exercises: 2
---


Depending on which devices you are supporting, you can
publishing content in an application store of each device:

- [Steam](https://store.steampowered.com/), for headsets
including HTC Vive or Vive Pro, HP Reverb G2
- [Meta Quest](https://www.meta.com/en-gb/experiences/), for headsets
including Oculus Rift, Oculus Go, Oculus Quest,  Samsung Gear VR
- [Microsoft Store](https://www.microsoft.com/en-us/store/collections/hlgettingstarted/hololens)

## How to publish?

To publish in one of these stores you will need to 
enroll to publish in the online store.

For example, [Steamworks](https://partner.steamgames.com/)
offers tools and services for publishing VR. Steamworks offers
to become a partner, including as a:

- Game Developer or Publisher
- PC Café Program, including sites such as hospitals, universities, or libraries.	

For Oculus, there are two paths, publishing in the OculusStore has
an extensive approval process. This includes
doing a [technical review](https://developer.oculus.com/resources/publish-quest-req/).


The [Meta Quest AppLab](https://developer.oculus.com/manage/) offers an
alternative path.

To distribute, you can share your app via a URL, providing
direct access to the description page,
and an option to purchase or install the app. 

Consider joining, if you are planning to make
available your game after development.


## Recomendations for publishing interactive VR

VR applications
usually need to meet strict guidelines to be considered for distribution.

Examine the test plan for the [Meta Quest](https://developer.oculus.com/resources/publish-quest-req/#test-plan).

Here are some guidelines:

- Limit the number of triangles or vertices.
- Less than 1-2 million per frame.
- Don't always strive for photorealism, concentrate on the overall VR experience.
- Use as few textures as possible.
- Techniques such as texture compression can minimize texture bandwidth consumption.
- Optimize your script which handles the logic of the experience.




