---
title: 'Distribution 3 DoF Experiences'
teaching: 10
exercises: 2
---



## Examples of 3DoF Experiences

Some websites allow for accessing 360 immersive image-renders 
with suitable interfaces for the user to move using 3DoF. 
When they don't have access to a device,
such as a mobile phone,
users can use the mouse to manipulate the virtual camera.

This type of experience allows for the wider access.

See the following examples:
- [360 cities](https://www.360cities.net/)
- [Arts and Culture 360 videos](https://artsandculture.google.com/project/360-videos)

Beside delivering 3DoF content websites, it is also possible
to develop applications to be installed
on a device which allow interaction with this type of content.

## Developing 3DoF XR experiences on the web

For developing this type of experience,
the best option is to use an existing platform, or
your own code using HTML + Javascript libraries.

This type of viewer is called a photosphere viewer
as the image is mapped as a texture on a sphere.
Most platforms will only provide
the basic functionality to move around.
Hence, custom-made code is required to access 
more complex/interactive functionality.


Existing platforms include:

- [VR YouTube](https://vr.youtube.com/)
- [Facebook 360](https://www.facebook.com/Facebook360/)

You can also include your own viewer using existing libraries, for example:

- [Google VR view](https://developers.google.com/vr/develop/web/vrview-web)


These allow for rendering an image or a video on the web.



