---
title: 'Introduction'
teaching: 10
exercises: 2
---

:::::::::::::::::::::::::::::::::::::: questions 

- What are the ways to distribute XR experiences?
- What platforms are available for distributing XR experiences on the web?
- What needs to consider when publishing an XR experience?

::::::::::::::::::::::::::::::::::::::::::::::::

::::::::::::::::::::::::::::::::::::: objectives


- Have an awareness for the multiple types of platforms which are available to publish 3D content.
- Explain the difference between 3DOF and 6DOF XR experiences
- Demonstrate how to include pieces of code, figures, and nested challenge blocks

::::::::::::::::::::::::::::::::::::::::::::::::

## Topics in this lesson


This lecture covers topics related to the distribution of XR experiences or applications.

It particularly focus on the availability of these experiences through various platforms and devices.

It considers the types of platforms that are available in the domain.

:::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::: instructor

You can point out here to the links which can show the various links available.


::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::

::::::::::::::::::::::::::::::::::::: challenge 

## Challenge 1: What is an XR experience?

Explore which of the following could be consider an XR experience?

Decide why this is the case?

Reflect how will you make available such experience to a user?

- 360 panoramas/video
- Interactive larger-scale images
- Outdoor 360 audio recording 
- Immersive 3D-world
- Interactive 3D model


:::::::::::::::::::::::: solution 

## Output
 
All of these examples could be considered an XR experience.
Although all have different levels of interactivity, sensory
input
as well as user-freedoms for moving within the environment.

:::::::::::::::::::::::::::::::::

::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::


::::::::::::::::::::::::::::::::::::: challenge 

## Challenge 2: How are XR experiences made available to users?

Explore how each of these experiences can be made available to users?

Reflect on how the distrubution platform might impact (or not) the amount 
of potential users.

:::::::::::::::::::::::: solution 


## Output
 

There are many different platforms for distributing XR experiences. 
Here is a list of the most popular ones.

- [Meta Quest](https://www.meta.com/en-gb/experiences/)
- [Valve Steam](https://store.steampowered.com/)
- [VR YouTube](https://vr.youtube.com/)
- [Facebook 360](https://www.facebook.com/Facebook360/)

Note that they distribute content both through a web browser and 
through a device such as a phone or headset.

Beside these platforms, XR experiences can be installed as apps
on mobile phones through platforms such as Google and Apple apps:

- [Apple App Store](https://apps.apple.com/)
- [Windows App Store](https://apps.microsoft.com/store/apps)
- [Google App Store](https://play.google.com/)

In most of these cases, the potential users is dependent on the
specific device they target.

:::::::::::::::::::::::::::::::::
::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::


